print("Olá, boa noite!");
print("Olá, digite seu nome.");
print("Bom dia! Digite seu endereço");
print("Bem vindo ao App");
print("Erro");
print("CEP inválido");
print("CPF inválido");
print("Digite seu logradouro");
print("Para qual time você torce?");
print("Em qual municipio você reside?");
print("Aula do Oldair");
print("Aula de Python");
print("Me chamo Yaggo");
print("Volte sempre!");
print("21 prints usando a linguagem python");
print("Faz 28 graus celsius em SP");
print("Senha inválida!");
print("Espere sua senha ser chamada");
print("Qual seu carro preferido?");
print("Rua Cubatão");
print("R$290,00");